# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # 使用最新的稳定版本
    hooks:
      - id: detect-forbidden-strings
        name: "Detect forbidden string zykj.hgyq365.cn"
        args:
          - --literal # 使用字面量匹配，而不是正则表达式
          - --forbidden-string=zykj.hgyq365.cn
          - --allow-replacement=zykjpre.hgyq365.cn # 提供建议的替换
        # 你可以排除某些文件，避免误报
        exclude: >
          (?x)^(
              path/to/some/ignored_file.md|
              \.pre-commit-config\.yaml
          )$
